name: 'Build Godot'
description: 'Build Godot with the provided options'
inputs:
  buildtype:
    description: 'The meson buildtype (debug/debugoptimized/optimized/minsize)'
    required: true
    default: 'debugoptimized'
  tools:
    description: 'If tools are to be built'
    required: true
    default: true
  platform:
    description: 'The Godot platform to build. This is currently unused'
    required: false
  meson:
    description: 'The meson binary to run (in case we need upstream/downstram patches to the build system).'
    required: true
    default: 'meson'
  destination:
    required: true
    default: 'builddir'
  mesonflags:
    default: ''
runs:
  using: "composite"
  steps:
    - name: Meson Configure
      shell: bash
      run: |
          ${{ inputs.meson }} ${{ inputs.destination }} ${{ inputs.mesonflags }} -Dbuildtype=${{ inputs.buildtype }} -Dtools=${{ inputs.tools }}
    - name: Meson compile
      shell: bash
      run: |
          ${{ inputs.meson }} compile -C ${{ inputs.destination }}
