name: 🤖 Android Meson Builds
on: [push, pull_request]

# Global Settings
env:
  GODOT_BASE_BRANCH: master
  MESONFLAGS: ""
  # platform=android verbose=yes warnings=extra werror=yes debug_symbols=no --jobs=2 module_text_server_fb_enabled=yes
  SCONS_CACHE_LIMIT: 4096

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  android-template:
    runs-on: "ubuntu-20.04"

    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        id: android-template-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}
        continue-on-error: true

      - name: Setup python and meson
        uses: ./.github/actions/meson_install

      - name: Generate meson cross compilation file (armv7a, aarch64).
        run: |
          python3 misc/scripts/make_android_cross.py "$ANDROID_NDK_ROOT" -m armv7a -o cross/android.armv7a.gen.txt
          python3 misc/scripts/make_android_cross.py "$ANDROID_NDK_ROOT" -m aarch64 -o cross/android.aarch64.gen.txt

      - name: Compilation (armv7a)
        uses: ./.github/actions/meson_build
        with:
          mesonflags: ${{ env.MESONFLAGS }} --cross-file cross/android.armv7a.gen.txt
          buildtype: release
          tools: false

      - name: Compilation (armv7a)
        uses: ./.github/actions/meson_build
        with:
          mesonflags: ${{ env.MESONFLAGS }} --cross-file cross/android.aarch64.gen.txt
          buildtype: release
          tools: false

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
