name: 🍎 macOS Meson Builds
on: [push, pull_request]

# Global Settings
env:
  GODOT_BASE_BRANCH: master
  MESONFLAGS: ''
  # platform=osx verbose=yes warnings=extra werror=yes debug_symbols=no --jobs=2 module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos-meson
  cancel-in-progress: true

jobs:
  macos-editor:
    runs-on: "macos-latest"

    name: Editor (target=release_debug, tools=yes, tests=yes)

    steps:
      - uses: actions/checkout@v2

      - name: Setup python and meson
        uses: ./.github/actions/meson_install

      - uses: ./.github/actions/meson_build
        name: Compilation
        with:
          mesonflags: ${{ env.MESONFLAGS }} -Dtests=true
          buildtype: debugoptimized
          tools: true

      # Execute unit tests for the editor
      - name: Unit Tests
        run: |
          ./builddir/godot --test

      - uses: ./.github/actions/upload-artifact

  macos-template:
    runs-on: "macos-latest"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      - name: Setup python and meson
        uses: ./.github/actions/meson_install

      - uses: ./.github/actions/meson_build
        name: Compilation
        with:
          mesonflags: ${{ env.MESONFLAGS }}
          buildtype: release
          tools: false

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
