name: 'Setup python meson ninja.'
description: 'Setup python installation, and install pip version of meson and ninja.'
inputs:
  python-version:
    description: 'The python version to use'
    required: true
    default: '3.x'
  python-arch:
    description: 'The python architecture'
    required: true
    default: 'x64'
runs:
  using: "composite"
  steps:
    # Use python 3.x release (works cross platform)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: ${{ inputs.python-version }}
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: ${{ inputs.python-arch }}
    - name: Setup meson and ninja
      shell: bash
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install meson ninja
        python --version
        meson --version
        ninja --version
